### ISSUE TITLE
fsck should check empty and unused mft entry(0x0B ~ 0x0F and 0x10 ~ 0x17) in system meta filemap

### ISSUE THREAD

**Issue by namjaejeon** [namjaejeon/ntfsprogs#10]
On a freshly formatted volume, inodes 0x0B to 0x0F are marked as in use, but empty. Inodes 0x10 to 0x17 are marked as free and not used. This doesn't change until the volume is under a lot of stress. how do fsck check it ?

**Comment by jaysim** [comment]
> inodes 0x0B to 0x0F are marked as in use, but empty

Does you mean 0x0B ~ 0x0F mft entry's in_use field is set, or bitmap of them is occupied?
I'd also checked 0x0C ~0x0F is occupied(bitmap) but looks like not used. I also don't know those inode is what for.

>  Inodes 0x10 to 0x17 are marked as free and not used.

I think those inodes is not problem, they will be used someday according to node allocation algorithm of ntfs(kernel).
